name: My First Workflow 1

on:
  # Manually trigger the workflow from the GitHub UI
  workflow_dispatch:

  # Trigger the workflow when there is a push to the main branch
  push:
    branches:
      - main

  # Trigger the workflow when a pull request is opened, synchronized, or reopened targeting the main branch
  pull_request:
    branches:
      - main

  # Trigger the workflow according to a schedule
  # This example runs the workflow at 5:00 AM, Monday through Friday
  schedule:
    - cron: '0 5 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Check out repository
        uses: actions/checkout@v3

      # Set up Node.js environment with the latest version
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependencies
        run: npm ci 

      - name: Run tests
        run: npm tests 

      # Print a custom message
      - name: Print a message
        run: echo "Hello, world!"
